server:
  port: 8090
spring:
  application:
    name: "AutomaticFishFeeder"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:/home/pi/feederDB/feed
    username: admin
    password: admin123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    open-in-view: true
  profiles:
    active: default
  output:
    ansi:
      enabled: always